version: '3.8'

services:
  dev-db:
    image: postgres
    restart: always
    env_file:
      - .env.development
    #environment:
    #  - POSTGRES_USER=${DB_USER}
    #  - POSTGRES_PASSWORD=${DB_PASSWORD}
    #  - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - mataka_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bridge

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    container_name: nest_server
    environment:
      - PORT=${PORT}
    ports:
      - "3000:3000"
    depends_on:
      - dev-db
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - bridge

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: nest-pgadmin4
    env_file:
      - .env.development
    #environment:
    #  - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    #  - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - dev-db
    networks:
      - bridge
volumes:
  mataka_db:
#networks:
#  mataka-networks